# Generated by Django 5.0.3 on 2024-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_img',
            field=models.ImageField(default='delivered.jpg', upload_to='delivered_img'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_img',
            field=models.ImageField(default='invoicep.jpg', upload_to='invoice_img'),
        ),
    ]
